name: Create General Issue
description: Create General Issue
title: "Summary"
labels: []
assignees:
  - miguel-a-miranda
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this issue report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detail all the relevant information 
      Tip: You can write full markdown here!
      placeholder: Tell us what you see!      
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Insert links to other issues.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: attach
    attributes:
      label: Attachments
      description: |
        Attach files.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
